name: Workflow to Rerun

on:
  push:
    branches:
      - main

jobs:
  some-job:
    name: Some flaky job
    runs-on: ubuntu-latest
    steps:
      - name: failing step
        id: failure
        run: exit 1
      - name: retry-on-failure
        if: failure() && steps.failure.outcome == 'failure' && fromJSON(github.run_attempt) < 3
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          GH_DEBUG: api
        run: gh workflow run rerun.yml -F run_id=${{ github.run_id }}